export const INITIALDATA_REQUEST = "INITIALDATA_REQUEST";
export const INITIALDATA_SUCCESS = "INITIALDATA_SUCCESS";
export const INITIALDATA_FAIL = "INITIALDATA_FAIL";
export const PRODUCTS_REQUEST = "PRODUCTS_REQUEST";
export const PRODUCTS_SUCCESS = "PRODUCTS_SUCCESS";
export const PRODUCTS_FAIL = "PRODUCTS_FAIL";